[package]
name = "calvera-books"
version = "0.0.6"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = "0.8.2"
rand = { workspace = true }
calvera = { git = "https://github.com/kaizu-xyz/calvera.git", branch = "main" }

[[bench]]
name = "orderbook"
harness = false

# [[bench]]
# name = "orderbook_2"
# harness = false

[[bench]]
name = "orderbook_disruptor_batched"
harness = false

[[example]]
name = "profile_matching"
path = "profiling/profile_matching.rs"